---
- name: ansible reboot module demo
  hosts: all
  become: trie
  tasks:
    - name: reboot Host(s)
      ansible.builtin.reboot:
        msg: "reboot by ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: "whoami"
