---
# play1
- hosts: webservers
  sudo: yes

  tasks:
  - name: Ensure that Apache is installed
    yum: name=httpd state=present

  - name: Start Apache Services
    service: name=httpd enabled=yes state=started

# play2
- hosts: dbservers
  sudo: yes

  tasks:
  - name: Ensure MySQL is installed
    yum: name=mysql-server state=present

  - name: Start MySQL
    service: name=mysqld state=started

# play3
- hosts: webservers:dbservers
  sudo: yes

  tasks:
  - name: Stop IPTABLES NOW!!!
    service: name=iptables state=stopped
